# Generated by Django 5.2.17 on 2026-08-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=700),
        ),
    ]
