# Generated by Django 5.2.17 on 2026-08-26 14:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_generator', '0004_rename_discription_category_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('words_practiced', models.IntegerField(default=0, help_text='Слов попрактиковано')),
                ('correct_answers', models.IntegerField(default=0, help_text='Правильных ответов')),
                ('wrong_answers', models.IntegerField(default=0, help_text='Неправильных ответов')),
                ('new_words', models.IntegerField(default=0, help_text='Новых слов добавлено')),
                ('streak', models.IntegerField(default=0, help_text='Текущая серия')),
                ('best_streak', models.IntegerField(default=0, help_text='Лучшая серия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='video_gener_user_id_e2a3df_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
